language: node_js
node_js:
  - '14'

env:
  - HOST=localhost REACT_APP_URL=https://$HOST REACT_APP_SERVER_PORT=5000 API_HOST=https://testrant.internet.ee PUBLIC_API_HOST=https://www.internet.ee PUBLIC_API_KEY=4395743059dsfksdfyds8f7334 CLIENT_ID=eis_client_test CLIENT_SECRET=secret12345 ISSUER_URL=https://tara-test.ria.ee TOKEN_PATH=/oidc/token JWKS_PATH=/oidc/jwks AUTH_PATH=/oidc/authorize REDIRECT_URL=/auth/callback SESSION_SECRET=secret555555 HTTPS=true
