const contacts = [
    {
        id: "cfbfbb76-aed8-497a-91c1-48d82cbc4588",
        name: "Test Registrant",
        code: "TEST:REGISTRANT",
        ident: {
            code: "39988776655",
            type: "priv",
            country_code: "EE",
        },
        email: "test@registrant.ee",
        phone: "+372.1234567",
        fax: null,
        address: {
            street: null,
            zip: null,
            city: null,
            state: null,
            country_code: null,
        },
        auth_info: "16c57aa7c435b959179c7b",
        statuses: ["ok", "linked"],
        disclosed_attributes: [],
    },
    {
        id: "700829af-4bdd-4c5f-8389-f6568e2ba4ad",
        name: "Test Tech",
        code: "TEST:TECH",
        ident: {
            code: "12345678910",
            type: "priv",
            country_code: "EE",
        },
        email: "test@tech.ee",
        phone: "+372.1234567",
        fax: null,
        address: {
            street: null,
            zip: null,
            city: null,
            state: null,
            country_code: null,
        },
        auth_info: "32776bf4c1d6995e6aa657",
        statuses: ["ok", "linked"],
        disclosed_attributes: ["email", "name"],
    },
    {
        id: "528240a3-3f9e-4d9a-83a2-3b3a43cf0dc7",
        name: "Test Admin",
        code: "TEST:ADMIN",
        ident: {
            code: "10987654321",
            type: "priv",
            country_code: "EE",
        },
        email: "test@admin.ee",
        phone: "+372.1234567",
        fax: null,
        address: {
            street: null,
            zip: null,
            city: null,
            state: null,
            country_code: null,
        },
        auth_info: "0e81a4b9049eda45c823a9",
        statuses: ["ok", "linked"],
        disclosed_attributes: ["email"],
    },
]

export default contacts
