// User
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';

// Domains
export const FETCH_DOMAINS_REQUEST = 'FETCH_DOMAINS_REQUEST';
export const FETCH_DOMAINS_SUCCESS = 'FETCH_DOMAINS_SUCCESS';
export const FETCH_DOMAINS_FAILURE = 'FETCH_DOMAINS_FAILURE';

export const LOCK_DOMAIN_REQUEST = 'LOCK_DOMAIN_REQUEST';
export const LOCK_DOMAIN_SUCCESS = 'LOCK_DOMAIN_SUCCESS';

export const UNLOCK_DOMAIN_REQUEST = 'UNLOCK_DOMAIN_REQUEST';
export const UNLOCK_DOMAIN_SUCCESS = 'UNLOCK_DOMAIN_SUCCESS';

// Contacts
export const FETCH_CONTACT_REQUEST = 'FETCH_CONTACT_REQUEST';
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';
export const FETCH_CONTACT_FAILURE = 'FETCH_CONTACT_FAILURE';
export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_FAILURE = 'FETCH_CONTACTS_FAILURE';
